---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendnodeservice
spec:
  selector:
    matchLabels:
      run: frontendnodeservice
  replicas: 1
  template:
    metadata:
      labels:
        run: frontendnodeservice
    spec:
      containers:
      - name: frontendnodeservice
        image: docker.io/danielbryantuk/frontendnodeservice
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontendnodeservice
  labels:
    run: frontendnodeservice
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    run: frontendnodeservice


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verylargejavaservice
spec:
  selector:
    matchLabels:
      run: verylargejavaservice
  replicas: 1
  template:
    metadata:
      labels:
        run: verylargejavaservice
    spec:
      containers:
      - name: verylargejavaservice
        image: docker.io/danielbryantuk/verylargejavaservice
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: verylargejavaservice
  labels:
    run: verylargejavaservice
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: verylargejavaservice

---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  verylargejavaservice
spec:
  prefix: /verylargejavaservice
  service: verylargejavaservice:8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verylargedatastore
spec:
  selector:
    matchLabels:
      run: verylargedatastore
  replicas: 1
  template:
    metadata:
      labels:
        run: verylargedatastore
    spec:
      containers:
      - name: verylargejavaservice
        image: docker.io/danielbryantuk/verylargedatastore
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: verylargedatastore
  labels:
    run: verylargedatastore
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: verylargedatastore